# Generated by Django 5.0.6 on 2024-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('others', 'Others'), ('female', 'Female')], max_length=100),
        ),
    ]
